development:
  adapter: postgresql
  encoding: unicode
  database: hypeman_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hypeman_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: hypeman_production
  pool: 5
  host: localhost